micronaut:
  application:
    name: micronaut-examples
  caches:
    external-api-cache:
      maximumSize: 20
      expire-after-access: 10s
      expire-after-write: 10s
  http:
    services:
      exchangeratesapi:
        #        read-timeout: 1s
        #        connect-timeout: 1s
        followRedirects: false
        pool:
          enabled: true
        urls:
          - https://api.exchangeratesapi.io

# Management API
endpoints:
  all:
    enabled: true
    sensitive: false

